language: python
python:
    - '2.6'
    - '2.7'

install:
  - pip install pep8 pyflakes --use-mirrors
  - pip install -r requirements.txt --use-mirrors
script:
  - pep8 --exclude='_thrift' tryfer
  - find tryfer -not -path '*/_thrift*' -name '*.py' | xargs pyflakes
  - trial tryfer
